### ISSUE TITLE
Need example of simulating a POST request with a body

### ISSUE THREAD

**Issue by vikasillumina** [SEEK-Jobs/seek.automation.stub#11]
Hi there,

We are using the pact based stub library where we have successfully generated the pact json files for our interactions. One of them is a POST api that we call with a body with just one name parameter for creating the entity. We were able to generate the PACT file just fine but however when we are invoking the API from our other test where we expect this api to respond to POST it throws error.
Here is our interaction that we are trying to simulate:
`{
      "description": "POST request for API to create a project",
      "providerState": "POST request for API to create a project",
      "request": {
        "method": "post",
        "path": "/v1/projects",
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "Name": "ProjectCreatedByStubService"
        }
      },
      "response": {
        "status": 201,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "Response": {
            "Id": "8215229",
            "Name": "ProjectCreatedByStubService"
          }
        }
      }
    }`

We suspect we might be doing missing something, so I was hoping if I can see an example of POST with a body may be I will be able to catch the issue.

Regards,
Vikas

**Comment by vikasillumina** [comment]
Anybody? :)

**Comment by neilcampbell** [comment]
Hi @vikasillumina 
I'm not sure this library has been updated in quite a while, so I'm guessing it may be stale and not compatible with the current version of Pact-Net.
What error are you getting?

**Comment by vikasillumina** [comment]
@neilcampbell I will send you the details of the error shortly. Thanks for looking into this.

**Comment by vikasillumina** [comment]
@neilcampbell here is the error we were getting:
`2018-10-03 17:39:01.451 -07:00 [Error] Stub on port 9000 says interaction not found. Please verify that the pact associated with this port contains the following request(case insensitive) : Method 'POST', Path '/v1/projects', Body '{"Name":"ProjectCreatedByMockService"}'. If you have specified filters please also check them.'

We were calling the stub Post method like this
` public HttpResponseMessage Post(string url, object requestObject)
        {
            var requestJson = JsonConvert.SerializeObject(requestObject);
            var request = new HttpRequestMessage(HttpMethod.Post, url)
            {
                Content = new StringContent(requestJson, Encoding.UTF8, "application/json")
            };
            return _httpClient.SendAsync(request).Result;
        }`

But just fiddling with this I changed below line:
`Content = new StringContent(requestJson, Encoding.UTF8, "application/json")`
to 
`Content = new StringContent(requestJson.ToString(), Encoding.UTF8, "application/json")`

and that seems to have resolved the issue.

On other thing we changed today was to start using the httpclient instead of RestSharp's RestClient, after we were following the example code here:
https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Consumer/EventsApiClient.cs 

Sorry we should have solved it ourselves sooner. Its just fresh day and fresh ideas to solve the same problem. :) 
Appreciate your time looking into this.

Regards,
Vikas
